const PAGE_TITLES = {
  home: "Turacoz Healthcare Solutions",
  about: "About | Turacoz Healthcare Solutions",
  contact: "Contact Us | Turacoz Healthcare Solutions",
  cources: "Courses | Turacoz Healthcare Solutions",
  webinar: "Webinar | Turacoz Healthcare Solutions",
  workshops: "Workshops | Turacoz Healthcare Solutions",
  institutional_training:
    "Institutional Training | Turacoz Healthcare Solutions",
  events: "Events | Turacoz Healthcare Solutions",
  career: "Career | Turacoz Healthcare Solutions",
  newsAndMedia: "News & Media | Turacoz Healthcare Solutions",
  value: "Our Values | Turacoz Healthcare Solutions",
  team: "Our Team | Turacoz Healthcare Solutions",
  Life: "Life At Turacoz | Turacoz Healthcare Solutions",
  resources: "Resources | Turacoz Healthcare Solutions",
  scientific:
    "Scientific and Medical Communication | Turacoz Healthcare Solutions",
  medical: "Medical Communication Strategy | Turacoz Healthcare Solutions",
  patient: "Patient Centric Communication | Turacoz Healthcare Solutions",
  medical_education: "Medical Education | Turacoz Healthcare Solutions",
  medical_information: "Medical Information | Turacoz Healthcare Solutions",
  OtherCommunication: "Other Communications | Turacoz Healthcare Solutions",
  reference: "Referencing And Annotation | Turacoz Healthcare Solutions",
  journal:
    "Journal Publications & Conference Presentation | Turacoz Healthcare Solutions",
  journalPublication: "Journal Publications | Turacoz Healthcare Solutions",
  PublicationPlaning: "Publication Planing | Turacoz Healthcare Solutions",
  PublicationSupport: "Publication Support | Turacoz Healthcare Solutions",
  PublicationDevelopement:
    "Publication Developement | Turacoz Healthcare Solutions",
  conference: "Conference Activities | Turacoz Healthcare Solutions",
  reformating: " Reformatting and Resubmission | Turacoz Healthcare Solutions",
  reviewComment:
    "Addressing Journal Review Comments | Turacoz Healthcare Solutions",
  literatureReview:
    "Systematic Literature Review and Targeted Literature Review  | Turacoz Healthcare Solutions",
  realWorld:
    " Real-World Evidence & Clinical Trial Services | Turacoz Healthcare Solutions",
  EOLEngagement:
    "Kol Engagement & Advocacy Building | Turacoz Healthcare Solutions",
  regulatoryWriting: "Regulatory Writing | Turacoz Healthcare Solutions",
  QCReview: "QC Review & Copy Editing | Turacoz Healthcare Solutions",
  ContentLabManagement: "Content Lab Management | Turacoz Healthcare Solutions",
  consultancy: "Consultancy | Turacoz Healthcare Solutions",
  LearningAndDevelopement:
    "Learning And Developement | Turacoz Healthcare Solutions",
};
const pageKeysArray = [
  "home",
  "about",
  "contact",
  "cources",
  "webinar",
  "workshops",
  "institutional_training",
  "events",
  "career",
  "newsAndMedia",
  "value",
  "team",
  "Life",
  "resources",
  "scientific",
  "medical",
  "patient",
  "medical_education",
  "medical_information",
  "OtherCommunication",
  "reference",
  "journal",
  "journalPublication",
  "PublicationPlaning",
  "PublicationSupport",
  "PublicationDevelopement",
  "conference",
  "reformating",
  "reviewComment",
  "literatureReview",
  "realWorld",
  "EOLEngagement",
  "regulatoryWriting",
  "QCReview",
  "ContentLabManagement",
  "consultancy",
  "LearningAndDevelopement",
];

export default PAGE_TITLES;
