const ABOUT_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_TURACOZ_TEAM_BEGIN: "GET_TURACOZ_TEAM_BEGIN",
  GET_TURACOZ_TEAM_SUCCESS: "GET_TURACOZ_TEAM_SUCCESS",
  GET_TURACOZ_TEAM_FAILURE: "GET_TURACOZ_TEAM_FAILURE",

  GET_LIFE_AT_TURACOZ_TEAM_BEGIN: "GET_LIFE_AT_TURACOZ_TEAM_BEGIN",
  GET_LIFE_AT_TURACOZ_TEAM_SUCCESS: "GET_LIFE_AT_TURACOZ_TEAM_SUCCESS",
  GET_LIFE_AT_TURACOZ_TEAM_FAILURE: "GET_LIFE_AT_TURACOZ_TEAM_FAILURE",

  GET_IMAGE_SLIDER_ABOUT_BEGIN: "GET_IMAGE_SLIDER_ABOUT_BEGIN",
  GET_IMAGE_SLIDER_ABOUT_SUCCESS: "GET_IMAGE_SLIDER_ABOUT_SUCCESS",
  GET_IMAGE_SLIDER_ABOUT_FAILURE: "GET_IMAGE_SLIDER_ABOUT_FAILURE",
};

export default ABOUT_TYPES;
