const BLOG_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_BLOG_LIST_BEGIN: "GET_BLOG_LIST_BEGIN",
  GET_BLOG_LIST_SUCCESS: "GET_BLOG_LIST_SUCCESS",
  GET_BLOG_LIST_FAILURE: "GET_BLOG_LIST_FAILURE",

  GET_BLOG_BYID_BEGIN: "GET_BLOG_BYID_BEGIN",
  GET_BLOG_BYID_SUCCESS: "GET_BLOG_BYID_SUCCESS",
  GET_BLOG_BYID_FAILURE: "GET_BLOG_BYID_FAILURE",

  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};

export default BLOG_TYPES;
