const CARRER_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_CARRER_LIST_BEGIN: "GET_CARRER_LIST_BEGIN",
    GET_CARRER_LIST_SUCCESS: "GET_CARRER_LIST_SUCCESS",
    GET_CARRER_LIST_FAILURE: "GET_CARRER_LIST_FAILURE",

    POST_CARRER_IMAGE_BEGIN: "POST_CARRER_IMAGE_BEGIN",
    POST_CARRER_IMAGE_SUCCESS: "POST_CARRER_IMAGE_SUCCESS",
    POST_CARRER_IMAGE_FAILURE: "POST_CARRER_IMAGE_FAILURE",
  
  };
  
  export default CARRER_TYPES;
  