const CASESTUDIES_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_CASESTUDIES_LIST_BEGIN: "GET_CASESTUDIES_LIST_BEGIN",
    GET_CASESTUDIES_LIST_SUCCESS: "GET_CASESTUDIES_LIST_SUCCESS",
    GET_CASESTUDIES_LIST_FAILURE: "GET_CASESTUDIES_LIST_FAILURE",

    GET_CASESTUDIES_BYID_BEGIN: "GET_CASESTUDIES_BYID_BEGIN",
    GET_CASESTUDIES_BYID_SUCCESS: "GET_CASESTUDIES_BYID_SUCCESS",
  GET_CASESTUDIES_BYID_FAILURE: "GET_CASESTUDIES_BYID_FAILURE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  
  };
  
  export default CASESTUDIES_TYPES;
  