const CONTACT_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    POST_CONTACT_BEGIN: "POST_CONTACT_BEGIN",
    POST_CONTACT_SUCCESS: "POST_CONTACT_SUCCESS",
    POST_CONTACT_FAILURE: "POST_CONTACT_FAILURE",
  };
  
  export default CONTACT_TYPES;
  