const COURSE_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_ALL_COURSE_LIST_BEGIN: "GET_ALL_COURSE_LIST_BEGIN",
    GET_ALL_COURSE_LIST_SUCCESS: "GET_ALL_COURSE_LIST_SUCCESS",
    GET_ALL_COURSE_LIST_FAILURE: "GET_ALL_COURSE_LIST_FAILURE",

    GET_COURSE_DETAIL_BEGIN: "GET_COURSE_DETAIL_BEGIN",
    GET_COURSE_DETAIL_SUCCESS: "GET_COURSE_DETAIL_SUCCESS",
    GET_COURSE_DETAIL_FAILURE: "GET_COURSE_DETAIL_FAILURE",
  
  };
  
  export default COURSE_TYPES;
  