const EVENT_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_EVENT_CONFERENCE_LIST_BEGIN: "GET_EVENT_CONFERENCE_LIST_BEGIN",
  GET_EVENT_CONFERENCE_LIST_SUCCESS: "GET_EVENT_CONFERENCE_LIST_SUCCESS",
  GET_EVENT_CONFERENCE_LIST_FAILURE: "GET_EVENT_CONFERENCE_LIST_FAILURE",

  GET_WEBINAR_CONFERENCE_LIST_BEGIN: "GET_WEBINAR_CONFERENCE_LIST_BEGIN",
  GET_WEBINAR_CONFERENCE_LIST_SUCCESS: "GET_WEBINAR_CONFERENCE_LIST_SUCCESS",
  GET_WEBINAR_CONFERENCE_LIST_FAILURE: "GET_WEBINAR_CONFERENCE_LIST_FAILURE",

  GET_EVENT_CONFERENCE_BYID_BEGIN: "GET_EVENT_CONFERENCE_BYID_BEGIN",
  GET_EVENT_CONFERENCE_BYID_SUCCESS: "GET_EVENT_CONFERENCE_BYID_SUCCESS",
  GET_EVENT_CONFERENCE_BYID_FAILURE: "GET_EVENT_CONFERENCE_BYID_FAILURE",

  GET_WEBINAR_CONFERENCE_BYID_BEGIN: "GET_WEBINAR_CONFERENCE_BYID_BEGIN",
  GET_WEBINAR_CONFERENCE_BYID_SUCCESS: "GET_WEBINAR_CONFERENCE_BYID_SUCCESS",
  GET_WEBINAR_CONFERENCE_BYID_FAILURE: "GET_WEBINAR_CONFERENCE_BYID_FAILURE",

  SET_EVENT_CONFERENCE_CURRENT_PAGE: "SET_EVENT_CONFERENCE_CURRENT_PAGE",

  SET_WEBINAR_CONFERENCE_CURRENT_PAGE: "SET_WEBINAR_CONFERENCE_CURRENT_PAGE",
};

export default EVENT_TYPES;
