const FOOTER_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_FOOTER_LIST_BEGIN: "GET_FOOTER_LIST_BEGIN",
    GET_FOOTER_LIST_SUCCESS: "GET_FOOTER_LIST_SUCCESS",
    GET_FOOTER_LIST_FAILURE: "GET_FOOTER_LIST_FAILURE",
  };
  
  export default FOOTER_TYPES;
  