const HEADER_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_HEADER_BEGIN: "GET_HEADER_BEGIN",
  GET_HEADER_SUCCESS: "GET_HEADER_SUCCESS",
  GET_HEADER_FAILURE: "GET_HEADER_FAILURE",
};

export default HEADER_TYPES;
