const HEADER_ADD_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_HEADER_ADD_LIST_BEGIN: "GET_HEADER_ADD_LIST_BEGIN",
  GET_HEADER_ADD_LIST_SUCCESS: "GET_HEADER_ADD_LIST_SUCCESS",
  GET_HEADER_ADD_LIST_FAILURE: "GET_HEADER_ADD_LIST_FAILURE",
};

export default HEADER_ADD_TYPES;
