const NEWSANDMEDIA_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_ANNOUNCEMENT_LIST_BEGIN: "GET_ANNOUNCEMENT_LIST_BEGIN",
  GET_ANNOUNCEMENT_LIST_SUCCESS: "GET_ANNOUNCEMENT_LIST_SUCCESS",
  GET_ANNOUNCEMENT_LIST_FAILURE: "GET_ANNOUNCEMENT_LIST_FAILURE",

  GET_PRESS_RELEASE_LIST_BEGIN: "GET_PRESS_RELEASE_LIST_BEGIN",
  GET_PRESS_RELEASE_LIST_SUCCESS: "GET_PRESS_RELEASE_LIST_SUCCESS",
  GET_PRESS_RELEASE_LIST_FAILURE: "GET_PRESS_RELEASE_LIST_FAILURE",

  GET_ANNOUNCEMENT_BYID_BEGIN: "GET_ANNOUNCEMENT_BYID_BEGIN",
  GET_ANNOUNCEMENT_BYID_SUCCESS: "GET_ANNOUNCEMENT_BYID_SUCCESS",
  GET_ANNOUNCEMENT_BYID_FAILURE: "GET_ANNOUNCEMENT_BYID_FAILURE",

  SET_ANNOUNCEMENT_CURRENT_PAGE: "SET_ANNOUNCEMENT_CURRENT_PAGE",

  SET_PRESS_RELEASE_CURRENT_PAGE: "SET_PRESS_RELEASE_CURRENT_PAGE",
};

export default NEWSANDMEDIA_TYPES;
