const NEWSLETTER_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_NEWSLETTER_LIST_BEGIN: "GET_NEWSLETTER_LIST_BEGIN",
  GET_NEWSLETTER_LIST_SUCCESS: "GET_NEWSLETTER_LIST_SUCCESS",
  GET_NEWSLETTER_LIST_FAILURE: "GET_NEWSLETTER_LIST_FAILURE",

  GET_NEWSLETTER_BYID_BEGIN: "GET_NEWSLETTER_BYID_BEGIN",
  GET_NEWSLETTER_BYID_SUCCESS: "GET_NEWSLETTER_BYID_SUCCESS",
  GET_NEWSLETTER_BYID_FAILURE: "GET_NEWSLETTER_BYID_FAILURE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};

export default NEWSLETTER_TYPES;
