const REQUEST_PROPOSAL_TYPES = {
  RESET_STATE: "RESET_STATE",

  POST_REQUEST_PROPOSAL_BEGIN: "POST_REQUEST_PROPOSAL_BEGIN",
  POST_REQUEST_PROPOSAL_SUCCESS: "POST_REQUEST_PROPOSAL_SUCCESS",
  POST_REQUEST_PROPOSAL_FAILURE: "POST_REQUEST_PROPOSAL_FAILURE",
};

export default REQUEST_PROPOSAL_TYPES;
