const USER_TYPES = {
  RESET_STATE: "RESET_STATE",

  POST_USERDETAILS_BEGIN: "POST_USERDETAILS_BEGIN",
  POST_USERDETAILS_SUCCESS: "POST_USERDETAILS_SUCCESS",
  POST_USERDETAILS_FAILURE: "POST_USERDETAILS_FAILURE",

  POST_NEWSLETTER_USERDETAILS_BEGIN: "POST_NEWSLETTER_USERDETAILS_BEGIN",
  POST_NEWSLETTER_USERDETAILS_SUCCESS: "POST_NEWSLETTER_USERDETAILS_SUCCESS",
  POST_NEWSLETTER_USERDETAILS_FAILURE: "POST_NEWSLETTER_USERDETAILS_FAILURE",
};

export default USER_TYPES;
