const WEBINAR_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_ALL_WEBINAR_LIST_BEGIN: "GET_ALL_WEBINAR_LIST_BEGIN",
  GET_ALL_WEBINAR_LIST_SUCCESS: "GET_ALL_WEBINAR_LIST_SUCCESS",
  GET_ALL_WEBINAR_LIST_FAILURE: "GET_ALL_WEBINAR_LIST_FAILURE",

  GET_WEBINAR_DETAIL_BEGIN: "GET_WEBINAR_DETAIL_BEGIN",
  GET_WEBINAR_DETAIL_SUCCESS: "GET_WEBINAR_DETAIL_SUCCESS",
  GET_WEBINAR_DETAIL_FAILURE: "GET_WEBINAR_DETAIL_FAILURE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};

export default WEBINAR_TYPES;
