const WHITEPAPER_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_WHITEPAPER_LIST_BEGIN: "GET_WHITEPAPER_LIST_BEGIN",
  GET_WHITEPAPER_LIST_SUCCESS: "GET_WHITEPAPER_LIST_SUCCESS",
  GET_WHITEPAPER_LIST_FAILURE: "GET_WHITEPAPER_LIST_FAILURE",

  GET_WHITEPAPER_BYID_BEGIN: "GET_WHITEPAPER_BYID_BEGIN",
  GET_WHITEPAPER_BYID_SUCCESS: "GET_WHITEPAPER_BYID_SUCCESS",
  GET_WHITEPAPER_BYID_FAILURE: "GET_WHITEPAPER_BYID_FAILURE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};

export default WHITEPAPER_TYPES;
