const WORKSHOP_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_ALL_WORKSHOP_LIST_BEGIN: "GET_ALL_WORKSHOP_LIST_BEGIN",
    GET_ALL_WORKSHOP_LIST_SUCCESS: "GET_ALL_WORKSHOP_LIST_SUCCESS",
    GET_ALL_WORKSHOP_LIST_FAILURE: "GET_ALL_WORKSHOP_LIST_FAILURE",
  
    GET_WORKSHOP_DETAIL_BEGIN: "GET_WORKSHOP_DETAIL_BEGIN",
    GET_WORKSHOP_DETAIL_SUCCESS: "GET_WORKSHOP_DETAIL_SUCCESS",
    GET_WORKSHOP_DETAIL_FAILURE: "GET_WORKSHOP_DETAIL_FAILURE",
  };
  
  export default WORKSHOP_TYPES;
  